# Generated by Django 5.2 on 2025-06-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Designation', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='employees')),
                ('Department', models.CharField(max_length=100)),
            ],
        ),
    ]
