# Generated by Django 5.2 on 2025-05-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Year', models.IntegerField()),
                ('Director_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='movies')),
            ],
        ),
    ]
